### ISSUE TITLE
 Enhance the UI of the Page

### ISSUE THREAD

**Issue by parulc7** [lugnitdgp/Tic-Tac-Toe#1]
Enhance the UI of the game page. CSS libraries like Bootstrap, Materialize etc. can also be used.

**Comment by jvdub** [comment]
I'm not exactly sure what you want on this one. I agree the UI needs some work, but it's hard to know what to do without an end-goal in mind. If you want, I can do my best and see what comes out. It may look a bit different than it does now, though.

**Comment by parulc7** [comment]
@jvdub  I would prefer a Instructions panel on the side or maybe a link to the instructions. As far as the game is concerned, try to use material design for the tiles.
